version: '3'
services:
    apache:
        build: docker/apache
        container_name: symfony-api-apache
        ports:
          - 80:80
        volumes:
          - ./docker/config/vhosts:/etc/apache2/sites-enabled
          - ./:/home/www/symfony-api
        depends_on:
          - php

    mysql:
        image: mysql:8
        container_name: symfony-api-mysql
        volumes:
            - ./docker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony-api
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    php:
        build: docker/php
        container_name: symfony-api-php
        volumes:
          - ./:/home/www/symfony-api
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: symfony-api-phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: symfony-api-maildev
        ports:
          - 8001:80
